### ISSUE TITLE
Publish flow as Admin

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#103]
As an admin or editor, I can publish my event. If I am missing required properties to publish, I want to get error messages. 
 
The required fields for being allowed to publish, for Tout Culture, are:
- title (in at least one language), 
- date, 
- location, 
- description of 50 minimum word count, 
- ticket info (free or price with info), 
- image
- audience type 
- one event type (at least one language)
- **supporter image (if supporter is linked to event)**

These required fields are NOT needed to save a draft event, only to publish.

In the future, we should add a feature to the calendar metadata that allows the admin to select the required fields to publish.

**Comment by SuhailAliyar** [comment]
@saumier lets discuss more about the ticket-info

**Comment by SuhailAliyar** [comment]
This feature can be tested once #157 is done

**Comment by saumier** [comment]
@SuhailAliyar See my comments in https://github.com/culturecreates/footlight-app/issues/29 about making the validation for offers more permissive.
