### ISSUE TITLE
Old CMS: Event keywords

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#131]
As a user (any role), I can add my own keywords to my event by typing in strings.  I can then search for events with the keyword I entered. There are no language settings (en,fr). The keyword can be in either language.

Note: Keywords are saved by event. Not reusable.

**Comment by saumier** [comment]
@SuhailAliyar I was not able to search my keywords using a query string in the Public API Swagger.

**Comment by SuhailAliyar** [comment]
Fixed issues with searching events by keywords. Also fixed issues with empty keyword field in event listing(Open API)

**Comment by saumier** [comment]
Please test oldcms in staging. You can add keywords to events and search for the events from the event listing screen.

**Comment by troughc** [comment]
Tested. Passed!
