### ISSUE TITLE
Old CMS - add support to persist keywords for events

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#156]
As a user, I can add multiple keywords to my event. I can create and delete keywords of my choosing. Keywords appear as tags in the keyword field with an 'x' to delete.

![Image](https://user-images.githubusercontent.com/419491/211557786-464f79b5-354c-4339-beee-095e331b801b.png)

**Comment by SuhailAliyar** [comment]
Added support to persist and list keywords for events in the backend. Assigning to @raseemayatt for UI changes.

**Comment by troughc** [comment]
Tested on Safari and Chrome- PASSED
