### ISSUE TITLE
Old CMS: Add support to upload image and logo for organizations

### ISSUE THREAD

**Issue by SuhailAliyar** [culturecreates/footlight-admin#157]
Add support to upload image for organization and a logo.  These are 2 separate fields. We can use the name "logo" for the logo field which comes from schema.org/logo.  I am assuming we have the same 3 sizes as for the image.

As a user, I can upload an image of the logo of my company. This is most important for organizations that sponsor an event, and want their logo displayed. **The logo should be nested in the organization in event details.**

**Comment by SuhailAliyar** [comment]
Added support to persist image and logo for organizations in the backend. Assigning to @raseemayatt for adding the same support in the Old CMS.

**Comment by saumier** [comment]
@culturecreates/artsdata-team Please test adding images and logos for organizations in oldcms.

**Comment by troughc** [comment]
Tested - PASSED - i was able to add the two different types of images. 
\
