### ISSUE TITLE
Old CMS: Add disambiguating descriptions

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#158]
In the Old CMS, add disambiguating descriptions to person, places and organizations. These are to appear in the combo-box when searching for places and organizations to link to an event.  Example: Performing arts centre in Montreal

![Image](https://user-images.githubusercontent.com/419491/211666564-f02fa8d4-556d-4345-ac62-e1ea64f94bf6.png)

**Comment by SuhailAliyar** [comment]
Added support in the backend. Assigning to @raseemayatt for adding support in the Old CMS.
