### ISSUE TITLE
Old CMS: fix invite email to match text for new CMS

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#159]
Old CMS: fix invite email to match text for new CMS

See the tab email copy in this spreadsheet:
https://docs.google.com/spreadsheets/d/1Wh2a-ZHVs94L7JPrgxv-sWRFm6_m7tfXSdPIln0GZiI/edit#gid=1337542326

**Comment by saumier** [comment]
@troughc Please check the email layout by inviting a guest using oldcms.

**Comment by troughc** [comment]
TESTED
Results
First:
email invitation ENGLISH preference looks good - I received the english version and I get an english UI when I go to the tool
email invitation FRENCH preference for UI - I received and ENGLISH email - Did not pass (but I get an French UI).
Second:
When I click 'ACCEPT INVITATION' I am taken to the OLD CMS, not the new one.

**Comment by saumier** [comment]
@SuhailAliyar Please look into why the French invite email is not being sent when the invitation has the user's UI set to French

**Comment by troughc** [comment]
@SuhailAliyar @saumier I am still getting the english email when I choose french preferences. please see screenshots.

SETTINGS

![Image](https://user-images.githubusercontent.com/64489312/214631694-e02e90c7-410c-41fa-8962-4f8c435cf2d3.png)

EMAIL

![Image](https://user-images.githubusercontent.com/64489312/214631739-ac375f74-aec7-4cc7-9b4b-fdcfa6d38515.png)

**Comment by troughc** [comment]
@SuhailAliyar @saumier Never mind - user error, I was in oldcms production. 
Tested in STAGING: PASSED
