### ISSUE TITLE
Old CMS - In the calendar Signé Laval (French only) cannot update Places

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#167]
To reproduce:
1. Select the Signé Laval calendar from the top left drop-down
2. Select a Place to edit
3. Click save --> you stay on the page and there is no error message

Expected behaviour: when saving a Place you are redirected to the place list screen.

Hint: In the bilingual calendar Tout Culture, there are 2 API calls. The first update the Postal address, and the second updates the Place. In the unilingual French Singé Laval calendar, there is only the first update Postal address call. The second call is never made.

**Comment by saumier** [comment]
@can you please test. Thx.

**Comment by troughc** [comment]
Tested
When fields are missing content, there is an error message displayed below the field(s) without content; when i add content and all required fields are filled, it saves.
Question @saumier - to save, all address fields are required except Province. Is this correct? If yes, then you can close this issue.

**Comment by saumier** [comment]
Organization totalCount not accurate.

https://staging.api.footlight.io/calendars/tout-culture/events?page=1&limit=11&query=dansa&start-date-range=2023-02-20



![Image](https://user-images.githubusercontent.com/419491/216986874-301e30ce-bc80-498c-8d54-2026ff6112b4.png)
