### ISSUE TITLE
Old CMS: Display Organization contact details

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#179]
As a user, I can create a contact for an Organization and view the details of the contact on the Organization screen, similar to the way I manage contacts in the Event screen.

**Comment by saumier** [comment]
@SuhailAliyar For the implementation of contacts, I was not sure if we should nest entities in the organization or keep them in a separate collection. What do you think?

**Comment by SuhailAliyar** [comment]
We nested contacts with the impression that the contact will never be reused. If contact is moved to a separate collection, then all the contacts(events, places, etc) should also be linked to the contact collection for making it homogeneous.

**Comment by saumier** [comment]
@SuhailAliyar We also want to be able to edit the contact (similar to offers) in both the organization and the event.

**Comment by saumier** [comment]
@saumier Also test virtual event.

**Comment by saumier** [comment]
@SuhailAliyar You mentioned that you fixed something with virtual event. Was it causing events to disappear. Minimal is still getting disappearing events when they edit in old CMS. 

Minial's comment: "After updating an event, when I go back to the list in the backend, the event I was updating does not always appear in the list. Ex: 63e392818679d90064a531a3"
https://oldcms.footlight.io/admin/add-event/?id=63e392818679d90064a531a3

**Comment by saumier** [comment]
@SuhailAliyar Lets push this to production on Friday at the latest.
