### ISSUE TITLE
Old CMS: fix street address from Google Places

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#199]
Fix street address to not include city, country, postal code from Google Places.

The street address should only contain street number and street name (route).  There should not be a country, city, province or postal code.

Example code from another project using Google Places API where extract_type() gets the first 'short_name'
```
    street_number = extract_type(address_components, "street_number") 
    route = extract_type(address_components, "route") 
    street_address = "#{street_number if street_number} #{route}".strip
```

In the screen grab below, the street address was manually edited by removing "Gatineau, QC J8Y 3G5, Canada" which was added by Google Places.

![Image](https://user-images.githubusercontent.com/419491/225688824-6801c560-5db1-4a1c-9eca-210734751fdd.png)

**Comment by AbhishekPAnil** [comment]
Estimate: 2
1.Remove the fields  country, city, province and postal code.
2.Remove the api integration for  country, city, province and postal code.
