### ISSUE TITLE
Old CMS: Bug creating org/place/etc.

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#201]
Unable to create a new Organization.  Also check other entities for same issue: Event, Person and Place.

![Image](https://user-images.githubusercontent.com/419491/228847602-dc3f9937-8e96-4a7d-8720-23e35d744960.png)

**Comment by troughc** [comment]
Tested on Chrome in old cms - 
Created a person: PASSED
Created Org: PASSED
Added concept to, and deleted from, taxonomy: PASSED
Added place: PASSED
