### ISSUE TITLE
Old CMS: Cannot add sameAs

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#218]
As a user of Old CMS, I would like to add sameAs to People.

Current behaviour: When I add a sameAs and click "update", when I return the sameAs is empty.

Example: http://kg.artsdata.ca/resource/K2-1703  is the URL to add to the sameAs field for the person Derrick Frenette.
http://oldcms.footlight.io/admin/add-person/?id=644964a3c54c9f0064e329ec

**Comment by AbhishekPAnil** [comment]
@SuhailAliyar sameAs  is becoming an empty while updating the people.Could you please look into this?
