### ISSUE TITLE
Old CMS: Add People

### ISSUE THREAD

**Issue by saumier** [culturecreates/footlight-admin#97]
Add People. See Figma for the fields. Include a disambiguating description.

## Test Cases
1. Create a person with a name fr, disambiguating description fr and occupation (custom taxonomy)
2. Link the person as a performer of an event
3. Link an organization as a performer of the same event

**Comment by SuhailAliyar** [comment]
@raseemayatt Please modify the validation message "Contact name required".

**Comment by troughc** [comment]
Tested on CHROME-Oldcms-staging. Created "Matt Lang" person: http://staging.oldcms.footlight.io/admin/add-person/?id=63c70a2bf01ab40070f3f338
Test 1 - fill all fields with data. ONE BUG: the 'Occupation field (linked to Occupation taxonomy) does not persist after I click Save or Update. I tried this multiple times on CHROME and retested adding an occupation on SAFARI but was unable to.

**Comment by saumier** [comment]
@troughc Back to you.

**Comment by troughc** [comment]
Tested in chrome: PASS
